---

parser: babel-eslint

globals:
    it: true
    expect: true
    describe: true

extends:
- airbnb

plugins:
- react

settings:
    import/extensions: ['.js']

rules:
    indent:
        - 2
        - 4
        - SwitchCase: 1
    react/jsx-indent-props:
        - 2
        - 4
    react/jsx-indent:
        - 2
        - 4
    semi: 2
    max-len:
        - 2
        - 100


    #loosening airbnb defaults
    array-bracket-spacing: 0
    no-else-return: 0
    object-curly-spacing: 0
    no-console: 0
    prefer-const: 0
    comma-dangle: 0
    func-names: 0
    no-underscore-dangle: 0
    no-unused-expressions: 0
    spaced-comment: 0
    vars-on-top: 0
    no-var: 0
    prefer-template: 0
    no-use-before-define: 0
    global-require: 0
    eol-last: 0
    one-var-declaration-per-line: 0
    one-var: 0
    eqeqeq: 0
    prefer-arrow-callback: 0
    radix: 0
