---

parser: babel-eslint

globals:
    it: true
    expect: true
    describe: true
    __DEV__: true
    fs: true
    tempDir: true
    downloadHttpFile: true
    fileExists: true
    readFile: true
    writeFile: true
    mkdir: true
    DOMParser: true
    $iq: true
    $pres: true
    $msg: true
    XMLHttpRequest: true
    Strophe: true
    navigator: true
    fetch: true
    getImageSize: true
    FormData: true
    step: true
    jest: true

extends:
  - airbnb

plugins:
  - flowtype

settings:
  import/extensions: ['.js']

rules:
  indent:
    - 2
    - 2
    - SwitchCase: 1
  react/jsx-indent-props:
    - 2
    - 2
  react/jsx-indent:
    - 2
    - 2
  semi: 2
  max-len:
    - 2
    - 180
  jsx-quotes:
    - 2
    - prefer-single
  object-curly-spacing:
    - 1
    - never
  flowtype/space-after-type-colon:
    - 2
  import/no-unresolved:
    - 1
    - ignore:
      - .png
      - .svg
      - .gif

  #loosening airbnb defaults
  array-bracket-spacing: 0
  no-else-return: 0
  func-names: 0
  no-underscore-dangle: 0
  no-var: 0
  global-require: 0
  one-var-declaration-per-line: 0
  one-var: 0
  radix: 0
  no-alert: 0
  no-use-before-define: 0
  arrow-body-style: 0
  no-unused-expressions: 0
  no-nested-ternary: 0
  import/first: 0
  class-methods-use-this: 0
  no-param-reassign: 0
  no-return-assign: 0
  object-curly-newline: 0
  arrow-parens: 1
  comma-dangle: 1
  no-plusplus: 0

  # warnings that should eventually be converted to errors
  no-mixed-operators: 0
  camelcase: 1
  no-throw-literal: 1
  eqeqeq: 1
  no-unused-vars: 1
  no-shadow: 1
  vars-on-top: 1
  default-case: 1
  no-restricted-syntax: 1
  import/no-duplicates: 1
  consistent-return: 1
  no-return-await: 1
  prefer-const: 1
  no-useless-constructor: 1
  no-useless-concat: 1
  no-bitwise: 1
  import/extensions: 1
  no-await-in-loop: 1
  no-prototype-builtins: 1
  no-continue: 1
  import/no-extraneous-dependencies: 1
  prefer-destructuring: 0
  prefer-promise-reject-errors: 1
  no-console: 1
  no-restricted-globals: 1
