---

parser: babel-eslint

globals:
    it: true
    expect: true
    describe: true

extends:
- airbnb

plugins:
- react

settings:
    import/extensions: ['.js']

rules:
    indent:
        - 2
        - 4
        - SwitchCase: 1
    react/jsx-indent-props:
        - 2
        - 4
    react/jsx-indent:
        - 0
        - 4
    semi: 2
    max-len:
        - 2
        - 150
    jsx-quotes:
        - 2
        - prefer-single
    object-curly-spacing:
        - 2
        - never
    import/no-unresolved:
        - 2
        - ignore:
            - .png
            - .svg
            - .gif


    #loosening airbnb defaults
    array-bracket-spacing: 0
    no-else-return: 0
    no-console: 0
    func-names: 0
    no-underscore-dangle: 0
    no-var: 0
    global-require: 0
    one-var-declaration-per-line: 0
    one-var: 0
    radix: 0
    react/sort-comp: 0
    no-alert: 0
    no-use-before-define: 0
    arrow-body-style: 0
    no-unused-expressions: 0
