const botStore = {
  geoKeyCache: [],
  bot: {
    removedItems: [],
    newAffiliates: [],
    removedAffiliates: [],
    followMe: false,
    isCurrent: true,
    followMeMinutes: 0,
    descriptionChanged: false,
    id: '951471d4-6049-11e7-b62e-0e2ac49618c7',
    loaded: true,
    isFollowed: false,
    isSubscribed: false,
    title: 'Dada',
    shortname: null,
    image: null,
    thumbnail: null,
    _images: [],
    _thumbnails: [],
    notes: [],
    tags: [],
    imageSaving: false,
    noteSaving: false,
    tagSaving: false,
    description: '',
    location: {longitude: -118.3466929, latitude: 34.0879041, accuracy: 5},
    radius: 30000,
    address: '907 N Formosa Ave, Los Angeles, CA 90046, USA',
    visibility: 0,
    visibilityShown: false,
    image_items: 0,
    followersSize: 0,
    affiliates: [],
    subscribers: [],
    _updated: 1499125480740,
    isNew: true,
    shareSelect: [],
    server: 'staging.dev.tinyrobot.com',
    type: 'location',
    owner: {
      user: '5b28b19c-46fe-11e7-8211-0e2ac49618c7',
      firstName: 'Eric',
      lastName: 'Kirkham',
      handle: 'kirkham1',
      tagline: '',
      avatar: null,
      email: 'eric@hippware.com',
      phoneNumber: '+1555',
      loaded: true,
      isFollower: false,
      isFollowed: false,
      isNew: false,
      isBlocked: false,
      hidePosts: false,
      status: 'available',
      followersSize: '4',
      botsSize: '22',
      isValid: false,
      followedSize: '4',
    },
  },
  address: {
    text: '907 N Formosa Ave, Los Angeles, CA 90046, USA',
    suggestions: [{place_name: '907 North Formosa Avenue, Los Angeles, CA 90046, USA', place_id: 'ChIJf9tV-NW-woAR0SudEpSLNEA'}],
    location: {longitude: -118.3466929, latitude: 34.0879041, accuracy: 5},
  },
};

export default botStore;
