// flow-typed signature: 8b14852c21dc133819cce2965a8f0377
// flow-typed version: <<STUB>>/apsl-react-native-button_v^3.0.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apsl-react-native-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apsl-react-native-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apsl-react-native-button/__tests__/Button.test' {
  declare module.exports: any;
}

declare module 'apsl-react-native-button/Button' {
  declare module.exports: any;
}

declare module 'apsl-react-native-button/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'apsl-react-native-button/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apsl-react-native-button/__tests__/Button.test.js' {
  declare module.exports: $Exports<'apsl-react-native-button/__tests__/Button.test'>;
}
declare module 'apsl-react-native-button/Button.js' {
  declare module.exports: $Exports<'apsl-react-native-button/Button'>;
}
declare module 'apsl-react-native-button/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'apsl-react-native-button/coverage/lcov-report/prettify'>;
}
declare module 'apsl-react-native-button/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'apsl-react-native-button/coverage/lcov-report/sorter'>;
}
