// flow-typed signature: cf1ecd93ec3ba56b278be718e195b788
// flow-typed version: <<STUB>>/autobind_v^1.0.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autobind'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'autobind' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'autobind/autobind' {
  declare module.exports: any;
}

// Filename aliases
declare module 'autobind/autobind.js' {
  declare module.exports: $Exports<'autobind/autobind'>;
}
