// flow-typed signature: 7b1b0b3ec1d07ed16ce634e215722e9b
// flow-typed version: <<STUB>>/mocha-steps_v^0.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-steps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-steps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha-steps/lib/step' {
  declare module.exports: any;
}

declare module 'mocha-steps/test/it' {
  declare module.exports: any;
}

declare module 'mocha-steps/test/step' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha-steps/lib/step.js' {
  declare module.exports: $Exports<'mocha-steps/lib/step'>;
}
declare module 'mocha-steps/test/it.js' {
  declare module.exports: $Exports<'mocha-steps/test/it'>;
}
declare module 'mocha-steps/test/step.js' {
  declare module.exports: $Exports<'mocha-steps/test/step'>;
}
