// flow-typed signature: 4797650020cb3891e0f43a12f75a969d
// flow-typed version: <<STUB>>/phoneformat.js_vgithub:hippware/phoneformat.js/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'phoneformat.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'phoneformat.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'phoneformat.js/dist/phone-format-amd' {
  declare module.exports: any;
}

declare module 'phoneformat.js/dist/phone-format-amd.min' {
  declare module.exports: any;
}

declare module 'phoneformat.js/dist/phone-format-exports' {
  declare module.exports: any;
}

declare module 'phoneformat.js/dist/phone-format-exports.min' {
  declare module.exports: any;
}

declare module 'phoneformat.js/dist/phone-format-global' {
  declare module.exports: any;
}

declare module 'phoneformat.js/dist/phone-format-global.min' {
  declare module.exports: any;
}

declare module 'phoneformat.js/dist/phone-format' {
  declare module.exports: any;
}

declare module 'phoneformat.js/dist/phone-format.min' {
  declare module.exports: any;
}

declare module 'phoneformat.js/Gruntfile' {
  declare module.exports: any;
}

declare module 'phoneformat.js/lib/global-wrap-end' {
  declare module.exports: any;
}

declare module 'phoneformat.js/lib/global-wrap-start' {
  declare module.exports: any;
}

declare module 'phoneformat.js/lib/google-libraries' {
  declare module.exports: any;
}

declare module 'phoneformat.js/lib/phone-format-interface' {
  declare module.exports: any;
}

declare module 'phoneformat.js/tests/jquery' {
  declare module.exports: any;
}

declare module 'phoneformat.js/tests/phone-format-amd' {
  declare module.exports: any;
}

declare module 'phoneformat.js/tests/qunit' {
  declare module.exports: any;
}

declare module 'phoneformat.js/tests/require' {
  declare module.exports: any;
}

declare module 'phoneformat.js/tests/test-runner' {
  declare module.exports: any;
}

declare module 'phoneformat.js/tests/unit/phone-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'phoneformat.js/dist/phone-format-amd.js' {
  declare module.exports: $Exports<'phoneformat.js/dist/phone-format-amd'>;
}
declare module 'phoneformat.js/dist/phone-format-amd.min.js' {
  declare module.exports: $Exports<'phoneformat.js/dist/phone-format-amd.min'>;
}
declare module 'phoneformat.js/dist/phone-format-exports.js' {
  declare module.exports: $Exports<'phoneformat.js/dist/phone-format-exports'>;
}
declare module 'phoneformat.js/dist/phone-format-exports.min.js' {
  declare module.exports: $Exports<'phoneformat.js/dist/phone-format-exports.min'>;
}
declare module 'phoneformat.js/dist/phone-format-global.js' {
  declare module.exports: $Exports<'phoneformat.js/dist/phone-format-global'>;
}
declare module 'phoneformat.js/dist/phone-format-global.min.js' {
  declare module.exports: $Exports<'phoneformat.js/dist/phone-format-global.min'>;
}
declare module 'phoneformat.js/dist/phone-format.js' {
  declare module.exports: $Exports<'phoneformat.js/dist/phone-format'>;
}
declare module 'phoneformat.js/dist/phone-format.min.js' {
  declare module.exports: $Exports<'phoneformat.js/dist/phone-format.min'>;
}
declare module 'phoneformat.js/Gruntfile.js' {
  declare module.exports: $Exports<'phoneformat.js/Gruntfile'>;
}
declare module 'phoneformat.js/lib/global-wrap-end.js' {
  declare module.exports: $Exports<'phoneformat.js/lib/global-wrap-end'>;
}
declare module 'phoneformat.js/lib/global-wrap-start.js' {
  declare module.exports: $Exports<'phoneformat.js/lib/global-wrap-start'>;
}
declare module 'phoneformat.js/lib/google-libraries.js' {
  declare module.exports: $Exports<'phoneformat.js/lib/google-libraries'>;
}
declare module 'phoneformat.js/lib/phone-format-interface.js' {
  declare module.exports: $Exports<'phoneformat.js/lib/phone-format-interface'>;
}
declare module 'phoneformat.js/tests/jquery.js' {
  declare module.exports: $Exports<'phoneformat.js/tests/jquery'>;
}
declare module 'phoneformat.js/tests/phone-format-amd.js' {
  declare module.exports: $Exports<'phoneformat.js/tests/phone-format-amd'>;
}
declare module 'phoneformat.js/tests/qunit.js' {
  declare module.exports: $Exports<'phoneformat.js/tests/qunit'>;
}
declare module 'phoneformat.js/tests/require.js' {
  declare module.exports: $Exports<'phoneformat.js/tests/require'>;
}
declare module 'phoneformat.js/tests/test-runner.js' {
  declare module.exports: $Exports<'phoneformat.js/tests/test-runner'>;
}
declare module 'phoneformat.js/tests/unit/phone-test.js' {
  declare module.exports: $Exports<'phoneformat.js/tests/unit/phone-test'>;
}
