// flow-typed signature: a4ddc2044d3c144d246d2c5f7642e039
// flow-typed version: <<STUB>>/react-native-parsed-text_v0.0.16/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-parsed-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-parsed-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-parsed-text/src/lib/TextExtraction' {
  declare module.exports: any;
}

declare module 'react-native-parsed-text/src/ParsedText' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-parsed-text/src/lib/TextExtraction.js' {
  declare module.exports: $Exports<'react-native-parsed-text/src/lib/TextExtraction'>;
}
declare module 'react-native-parsed-text/src/ParsedText.js' {
  declare module.exports: $Exports<'react-native-parsed-text/src/ParsedText'>;
}
