// flow-typed signature: ecf534cd88990bea58f7db924f1b03e6
// flow-typed version: <<STUB>>/react-native-cube-transition_vgithub:hippware/react-native-cube-transition#1e473754642763b9d8396c9bd463ed454c447dd7/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-cube-transition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-cube-transition' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-cube-transition/addNavigationHelpers' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/CubeTabNavigator' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/CubeView' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/NavigationActions' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/RNCubeTransition.ios' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/SceneView' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/TabView' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/TabViewPagerAndroid' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/TabViewPagerCube' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/TabViewPagerPan' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/TabViewPagerScroll' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/TabViewPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/TabViewTypeDefinitions' {
  declare module.exports: any;
}

declare module 'react-native-cube-transition/withCachedChildNavigation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-cube-transition/addNavigationHelpers.js' {
  declare module.exports: $Exports<'react-native-cube-transition/addNavigationHelpers'>;
}
declare module 'react-native-cube-transition/CubeTabNavigator.js' {
  declare module.exports: $Exports<'react-native-cube-transition/CubeTabNavigator'>;
}
declare module 'react-native-cube-transition/CubeView.js' {
  declare module.exports: $Exports<'react-native-cube-transition/CubeView'>;
}
declare module 'react-native-cube-transition/index' {
  declare module.exports: $Exports<'react-native-cube-transition'>;
}
declare module 'react-native-cube-transition/index.js' {
  declare module.exports: $Exports<'react-native-cube-transition'>;
}
declare module 'react-native-cube-transition/NavigationActions.js' {
  declare module.exports: $Exports<'react-native-cube-transition/NavigationActions'>;
}
declare module 'react-native-cube-transition/RNCubeTransition.ios.js' {
  declare module.exports: $Exports<'react-native-cube-transition/RNCubeTransition.ios'>;
}
declare module 'react-native-cube-transition/SceneView.js' {
  declare module.exports: $Exports<'react-native-cube-transition/SceneView'>;
}
declare module 'react-native-cube-transition/TabView.js' {
  declare module.exports: $Exports<'react-native-cube-transition/TabView'>;
}
declare module 'react-native-cube-transition/TabViewPagerAndroid.js' {
  declare module.exports: $Exports<'react-native-cube-transition/TabViewPagerAndroid'>;
}
declare module 'react-native-cube-transition/TabViewPagerCube.js' {
  declare module.exports: $Exports<'react-native-cube-transition/TabViewPagerCube'>;
}
declare module 'react-native-cube-transition/TabViewPagerPan.js' {
  declare module.exports: $Exports<'react-native-cube-transition/TabViewPagerPan'>;
}
declare module 'react-native-cube-transition/TabViewPagerScroll.js' {
  declare module.exports: $Exports<'react-native-cube-transition/TabViewPagerScroll'>;
}
declare module 'react-native-cube-transition/TabViewPropTypes.js' {
  declare module.exports: $Exports<'react-native-cube-transition/TabViewPropTypes'>;
}
declare module 'react-native-cube-transition/TabViewTypeDefinitions.js' {
  declare module.exports: $Exports<'react-native-cube-transition/TabViewTypeDefinitions'>;
}
declare module 'react-native-cube-transition/withCachedChildNavigation.js' {
  declare module.exports: $Exports<'react-native-cube-transition/withCachedChildNavigation'>;
}
