// flow-typed signature: 995efeee391971339a2c876c7eaf74da
// flow-typed version: <<STUB>>/react-native-swipeable_v^0.4.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-swipeable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-swipeable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-swipeable/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-swipeable/lib/index.js' {
  declare module.exports: $Exports<'react-native-swipeable/lib/index'>;
}
