// flow-typed signature: 72194213c836ecf7000c4cb6a4eea793
// flow-typed version: <<STUB>>/react-native-stateless-form_v^0.3.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-stateless-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-stateless-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-stateless-form/components/InlineTextInput' {
  declare module.exports: any;
}

declare module 'react-native-stateless-form/components/LabeledTextInput' {
  declare module.exports: any;
}

declare module 'react-native-stateless-form/StatelessForm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-stateless-form/components/InlineTextInput.js' {
  declare module.exports: $Exports<'react-native-stateless-form/components/InlineTextInput'>;
}
declare module 'react-native-stateless-form/components/LabeledTextInput.js' {
  declare module.exports: $Exports<'react-native-stateless-form/components/LabeledTextInput'>;
}
declare module 'react-native-stateless-form/index' {
  declare module.exports: $Exports<'react-native-stateless-form'>;
}
declare module 'react-native-stateless-form/index.js' {
  declare module.exports: $Exports<'react-native-stateless-form'>;
}
declare module 'react-native-stateless-form/StatelessForm.js' {
  declare module.exports: $Exports<'react-native-stateless-form/StatelessForm'>;
}
