// flow-typed signature: 7fa3d536c01b47092340db184cb80e5b
// flow-typed version: <<STUB>>/react-native-firebase_v^3.0.0-alpha.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-firebase/lib/firebase-app' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/firebase' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/flow' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/internals' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/AdMobComponent' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/AdRequest' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/Banner' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/EventTypes' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/Interstitial' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/NativeExpress' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/RewardedVideo' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/VideoOptions' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/analytics/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/ConfirmationResult' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/Email' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/Facebook' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/Github' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/Google' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/Phone' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/Twitter' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/user' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/base' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/config/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/crash/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/disconnect' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/query' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/reference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/snapshot' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/transaction' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/messaging/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/messaging/RemoteMessage' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/perf/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/perf/Trace' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/storage/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/storage/reference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/storage/task' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/emitter/EmitterSubscription' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/emitter/EventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/emitter/EventSubscription' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/emitter/EventSubscriptionVendor' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/log' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/ModuleBase' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/ReferenceBase' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/SyncTree' {
  declare module.exports: any;
}

declare module 'react-native-firebase/scratch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-firebase/index' {
  declare module.exports: $Exports<'react-native-firebase'>;
}
declare module 'react-native-firebase/index.js' {
  declare module.exports: $Exports<'react-native-firebase'>;
}
declare module 'react-native-firebase/lib/firebase-app.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/firebase-app'>;
}
declare module 'react-native-firebase/lib/firebase.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/firebase'>;
}
declare module 'react-native-firebase/lib/flow.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/flow'>;
}
declare module 'react-native-firebase/lib/internals.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/internals'>;
}
declare module 'react-native-firebase/lib/modules/admob/AdMobComponent.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/AdMobComponent'>;
}
declare module 'react-native-firebase/lib/modules/admob/AdRequest.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/AdRequest'>;
}
declare module 'react-native-firebase/lib/modules/admob/Banner.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/Banner'>;
}
declare module 'react-native-firebase/lib/modules/admob/EventTypes.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/EventTypes'>;
}
declare module 'react-native-firebase/lib/modules/admob/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/index'>;
}
declare module 'react-native-firebase/lib/modules/admob/Interstitial.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/Interstitial'>;
}
declare module 'react-native-firebase/lib/modules/admob/NativeExpress.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/NativeExpress'>;
}
declare module 'react-native-firebase/lib/modules/admob/RewardedVideo.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/RewardedVideo'>;
}
declare module 'react-native-firebase/lib/modules/admob/VideoOptions.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/VideoOptions'>;
}
declare module 'react-native-firebase/lib/modules/analytics/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/analytics/index'>;
}
declare module 'react-native-firebase/lib/modules/auth/ConfirmationResult.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/ConfirmationResult'>;
}
declare module 'react-native-firebase/lib/modules/auth/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/index'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/Email.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/Email'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/Facebook.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/Facebook'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/Github.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/Github'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/Google.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/Google'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/Phone.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/Phone'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/Twitter.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/Twitter'>;
}
declare module 'react-native-firebase/lib/modules/auth/user.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/user'>;
}
declare module 'react-native-firebase/lib/modules/base.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/base'>;
}
declare module 'react-native-firebase/lib/modules/config/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/config/index'>;
}
declare module 'react-native-firebase/lib/modules/crash/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/crash/index'>;
}
declare module 'react-native-firebase/lib/modules/database/disconnect.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/disconnect'>;
}
declare module 'react-native-firebase/lib/modules/database/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/index'>;
}
declare module 'react-native-firebase/lib/modules/database/query.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/query'>;
}
declare module 'react-native-firebase/lib/modules/database/reference.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/reference'>;
}
declare module 'react-native-firebase/lib/modules/database/snapshot.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/snapshot'>;
}
declare module 'react-native-firebase/lib/modules/database/transaction.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/transaction'>;
}
declare module 'react-native-firebase/lib/modules/messaging/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/messaging/index'>;
}
declare module 'react-native-firebase/lib/modules/messaging/RemoteMessage.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/messaging/RemoteMessage'>;
}
declare module 'react-native-firebase/lib/modules/perf/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/perf/index'>;
}
declare module 'react-native-firebase/lib/modules/perf/Trace.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/perf/Trace'>;
}
declare module 'react-native-firebase/lib/modules/storage/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/storage/index'>;
}
declare module 'react-native-firebase/lib/modules/storage/reference.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/storage/reference'>;
}
declare module 'react-native-firebase/lib/modules/storage/task.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/storage/task'>;
}
declare module 'react-native-firebase/lib/utils/emitter/EmitterSubscription.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/emitter/EmitterSubscription'>;
}
declare module 'react-native-firebase/lib/utils/emitter/EventEmitter.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/emitter/EventEmitter'>;
}
declare module 'react-native-firebase/lib/utils/emitter/EventSubscription.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/emitter/EventSubscription'>;
}
declare module 'react-native-firebase/lib/utils/emitter/EventSubscriptionVendor.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/emitter/EventSubscriptionVendor'>;
}
declare module 'react-native-firebase/lib/utils/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/index'>;
}
declare module 'react-native-firebase/lib/utils/log.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/log'>;
}
declare module 'react-native-firebase/lib/utils/ModuleBase.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/ModuleBase'>;
}
declare module 'react-native-firebase/lib/utils/ReferenceBase.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/ReferenceBase'>;
}
declare module 'react-native-firebase/lib/utils/SyncTree.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/SyncTree'>;
}
declare module 'react-native-firebase/scratch.js' {
  declare module.exports: $Exports<'react-native-firebase/scratch'>;
}
