// flow-typed signature: 09d3d4c445eb6344ffbe805c357fb02d
// flow-typed version: <<STUB>>/react-native-native-env_vgithub:aksonov/react-native-native-env/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-native-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-native-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-native-env/sample/index.android' {
  declare module.exports: any;
}

declare module 'react-native-native-env/sample/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-native-env/index' {
  declare module.exports: $Exports<'react-native-native-env'>;
}
declare module 'react-native-native-env/index.js' {
  declare module.exports: $Exports<'react-native-native-env'>;
}
declare module 'react-native-native-env/sample/index.android.js' {
  declare module.exports: $Exports<'react-native-native-env/sample/index.android'>;
}
declare module 'react-native-native-env/sample/index.ios.js' {
  declare module.exports: $Exports<'react-native-native-env/sample/index.ios'>;
}
