// flow-typed signature: a0b51541350a916a9fb3efecf0192616
// flow-typed version: <<STUB>>/react-native-mapbox-gl_vgithub:hippware/react-native-mapbox-gl#5.2.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-mapbox-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-mapbox-gl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-mapbox-gl/Annotation' {
  declare module.exports: any;
}

declare module 'react-native-mapbox-gl/example' {
  declare module.exports: any;
}

declare module 'react-native-mapbox-gl/scripts/download-mapbox-gl-native-ios-if-on-mac' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-mapbox-gl/Annotation.js' {
  declare module.exports: $Exports<'react-native-mapbox-gl/Annotation'>;
}
declare module 'react-native-mapbox-gl/example.js' {
  declare module.exports: $Exports<'react-native-mapbox-gl/example'>;
}
declare module 'react-native-mapbox-gl/index' {
  declare module.exports: $Exports<'react-native-mapbox-gl'>;
}
declare module 'react-native-mapbox-gl/index.js' {
  declare module.exports: $Exports<'react-native-mapbox-gl'>;
}
declare module 'react-native-mapbox-gl/scripts/download-mapbox-gl-native-ios-if-on-mac.js' {
  declare module.exports: $Exports<'react-native-mapbox-gl/scripts/download-mapbox-gl-native-ios-if-on-mac'>;
}
