// flow-typed signature: 138c0c54488dca02700a2f7447c32d10
// flow-typed version: <<STUB>>/react-native-fabric-digits_v^1.0.26/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fabric-digits'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fabric-digits' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-fabric-digits/DigitsLoginButton' {
  declare module.exports: any;
}

declare module 'react-native-fabric-digits/DigitsLogoutButton' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-fabric-digits/DigitsLoginButton.js' {
  declare module.exports: $Exports<'react-native-fabric-digits/DigitsLoginButton'>;
}
declare module 'react-native-fabric-digits/DigitsLogoutButton.js' {
  declare module.exports: $Exports<'react-native-fabric-digits/DigitsLogoutButton'>;
}
declare module 'react-native-fabric-digits/index' {
  declare module.exports: $Exports<'react-native-fabric-digits'>;
}
declare module 'react-native-fabric-digits/index.js' {
  declare module.exports: $Exports<'react-native-fabric-digits'>;
}
