// flow-typed signature: e8899ef3d18c427c6f154875415d32b2
// flow-typed version: <<STUB>>/react-native-swiper_v^1.5.12/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-swiper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-swiper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-swiper/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-swiper/index' {
  declare module.exports: $Exports<'react-native-swiper'>;
}
declare module 'react-native-swiper/index.js' {
  declare module.exports: $Exports<'react-native-swiper'>;
}
declare module 'react-native-swiper/src/index.js' {
  declare module.exports: $Exports<'react-native-swiper/src/index'>;
}
