// flow-typed signature: af3c8c16813bd45967bbb4e1567e577e
// flow-typed version: <<STUB>>/react-native-tabs_v^1.0.9/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-tabs/index' {
  declare module.exports: $Exports<'react-native-tabs'>;
}
declare module 'react-native-tabs/index.js' {
  declare module.exports: $Exports<'react-native-tabs'>;
}
