// flow-typed signature: 1f9d8a38045deaff1ea6cfbe011aa8a0
// flow-typed version: <<STUB>>/strophejs_vgithub:hippware/strophejs/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strophejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strophejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'strophejs/build' {
  declare module.exports: any;
}

declare module 'strophejs/contrib/discojs/scripts/basic' {
  declare module.exports: any;
}

declare module 'strophejs/contrib/discojs/scripts/disco' {
  declare module.exports: any;
}

declare module 'strophejs/examples/basic' {
  declare module.exports: any;
}

declare module 'strophejs/examples/echobot' {
  declare module.exports: any;
}

declare module 'strophejs/examples/main' {
  declare module.exports: any;
}

declare module 'strophejs/examples/prebind' {
  declare module.exports: any;
}

declare module 'strophejs/examples/restore' {
  declare module.exports: any;
}

declare module 'strophejs/Gruntfile' {
  declare module.exports: any;
}

declare module 'strophejs/main' {
  declare module.exports: any;
}

declare module 'strophejs/src/base64' {
  declare module.exports: any;
}

declare module 'strophejs/src/bosh' {
  declare module.exports: any;
}

declare module 'strophejs/src/core' {
  declare module.exports: any;
}

declare module 'strophejs/src/md5' {
  declare module.exports: any;
}

declare module 'strophejs/src/polyfills' {
  declare module.exports: any;
}

declare module 'strophejs/src/sha1' {
  declare module.exports: any;
}

declare module 'strophejs/src/utils' {
  declare module.exports: any;
}

declare module 'strophejs/src/websocket' {
  declare module.exports: any;
}

declare module 'strophejs/src/wrap_footer' {
  declare module.exports: any;
}

declare module 'strophejs/src/wrap_header' {
  declare module.exports: any;
}

declare module 'strophejs/src/wrapper' {
  declare module.exports: any;
}

declare module 'strophejs/strophe' {
  declare module.exports: any;
}

declare module 'strophejs/strophe.min' {
  declare module.exports: any;
}

declare module 'strophejs/tests/main' {
  declare module.exports: any;
}

declare module 'strophejs/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'strophejs/build.js' {
  declare module.exports: $Exports<'strophejs/build'>;
}
declare module 'strophejs/contrib/discojs/scripts/basic.js' {
  declare module.exports: $Exports<'strophejs/contrib/discojs/scripts/basic'>;
}
declare module 'strophejs/contrib/discojs/scripts/disco.js' {
  declare module.exports: $Exports<'strophejs/contrib/discojs/scripts/disco'>;
}
declare module 'strophejs/examples/basic.js' {
  declare module.exports: $Exports<'strophejs/examples/basic'>;
}
declare module 'strophejs/examples/echobot.js' {
  declare module.exports: $Exports<'strophejs/examples/echobot'>;
}
declare module 'strophejs/examples/main.js' {
  declare module.exports: $Exports<'strophejs/examples/main'>;
}
declare module 'strophejs/examples/prebind.js' {
  declare module.exports: $Exports<'strophejs/examples/prebind'>;
}
declare module 'strophejs/examples/restore.js' {
  declare module.exports: $Exports<'strophejs/examples/restore'>;
}
declare module 'strophejs/Gruntfile.js' {
  declare module.exports: $Exports<'strophejs/Gruntfile'>;
}
declare module 'strophejs/main.js' {
  declare module.exports: $Exports<'strophejs/main'>;
}
declare module 'strophejs/src/base64.js' {
  declare module.exports: $Exports<'strophejs/src/base64'>;
}
declare module 'strophejs/src/bosh.js' {
  declare module.exports: $Exports<'strophejs/src/bosh'>;
}
declare module 'strophejs/src/core.js' {
  declare module.exports: $Exports<'strophejs/src/core'>;
}
declare module 'strophejs/src/md5.js' {
  declare module.exports: $Exports<'strophejs/src/md5'>;
}
declare module 'strophejs/src/polyfills.js' {
  declare module.exports: $Exports<'strophejs/src/polyfills'>;
}
declare module 'strophejs/src/sha1.js' {
  declare module.exports: $Exports<'strophejs/src/sha1'>;
}
declare module 'strophejs/src/utils.js' {
  declare module.exports: $Exports<'strophejs/src/utils'>;
}
declare module 'strophejs/src/websocket.js' {
  declare module.exports: $Exports<'strophejs/src/websocket'>;
}
declare module 'strophejs/src/wrap_footer.js' {
  declare module.exports: $Exports<'strophejs/src/wrap_footer'>;
}
declare module 'strophejs/src/wrap_header.js' {
  declare module.exports: $Exports<'strophejs/src/wrap_header'>;
}
declare module 'strophejs/src/wrapper.js' {
  declare module.exports: $Exports<'strophejs/src/wrapper'>;
}
declare module 'strophejs/strophe.js' {
  declare module.exports: $Exports<'strophejs/strophe'>;
}
declare module 'strophejs/strophe.min.js' {
  declare module.exports: $Exports<'strophejs/strophe.min'>;
}
declare module 'strophejs/tests/main.js' {
  declare module.exports: $Exports<'strophejs/tests/main'>;
}
declare module 'strophejs/tests/tests.js' {
  declare module.exports: $Exports<'strophejs/tests/tests'>;
}
