// flow-typed signature: 192cb5b2e1eb0f47694ef6a29f35ac10
// flow-typed version: <<STUB>>/babel-plugin-mobx-deep-action_v^1.5.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-mobx-deep-action'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-mobx-deep-action' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-mobx-deep-action/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-mobx-deep-action/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-mobx-deep-action/lib/index'>;
}
