// flow-typed signature: 525a861234994dfd4c13bf3318d2dd58
// flow-typed version: <<STUB>>/cd_v^0.3.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cd/test' {
  declare module.exports: any;
}

declare module 'cd/test/lol' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cd/index' {
  declare module.exports: $Exports<'cd'>;
}
declare module 'cd/index.js' {
  declare module.exports: $Exports<'cd'>;
}
declare module 'cd/test.js' {
  declare module.exports: $Exports<'cd/test'>;
}
declare module 'cd/test/lol.js' {
  declare module.exports: $Exports<'cd/test/lol'>;
}
