// flow-typed signature: 78d9bfe1677acd88a64cd87ff5eb9c47
// flow-typed version: <<STUB>>/estraverse-fb_v^1.3.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'estraverse-fb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'estraverse-fb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'estraverse-fb/estraverse-fb' {
  declare module.exports: any;
}

declare module 'estraverse-fb/keys' {
  declare module.exports: any;
}

declare module 'estraverse-fb/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'estraverse-fb/estraverse-fb.js' {
  declare module.exports: $Exports<'estraverse-fb/estraverse-fb'>;
}
declare module 'estraverse-fb/keys.js' {
  declare module.exports: $Exports<'estraverse-fb/keys'>;
}
declare module 'estraverse-fb/test.js' {
  declare module.exports: $Exports<'estraverse-fb/test'>;
}
