// flow-typed signature: ea9914a7ffa81d153a5c246a89474570
// flow-typed version: <<STUB>>/libphonenumber-js_v^0.4.29/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libphonenumber-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libphonenumber-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libphonenumber-js/bin/update-metadata' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/as you type' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/common' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/format' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/get number type' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/metadata' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parse' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/tools/compress' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/tools/download' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/tools/generate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/validate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/bundle/input-format.min' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/bundle/libphonenumber-js.min' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/custom' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/as you type' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/common' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/format' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/get number type' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/metadata' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parse' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/tools/compress' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/tools/download' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/tools/generate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/validate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/index.common' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/index.es6' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/download' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/generate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/metadata-branch' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/metadata-pull-request' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/metadata-unbranch' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/update' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libphonenumber-js/bin/update-metadata.js' {
  declare module.exports: $Exports<'libphonenumber-js/bin/update-metadata'>;
}
declare module 'libphonenumber-js/build/as you type.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/as you type'>;
}
declare module 'libphonenumber-js/build/common.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/common'>;
}
declare module 'libphonenumber-js/build/format.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/format'>;
}
declare module 'libphonenumber-js/build/get number type.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/get number type'>;
}
declare module 'libphonenumber-js/build/metadata.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/metadata'>;
}
declare module 'libphonenumber-js/build/parse.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parse'>;
}
declare module 'libphonenumber-js/build/tools/compress.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/tools/compress'>;
}
declare module 'libphonenumber-js/build/tools/download.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/tools/download'>;
}
declare module 'libphonenumber-js/build/tools/generate.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/tools/generate'>;
}
declare module 'libphonenumber-js/build/validate.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/validate'>;
}
declare module 'libphonenumber-js/bundle/input-format.min.js' {
  declare module.exports: $Exports<'libphonenumber-js/bundle/input-format.min'>;
}
declare module 'libphonenumber-js/bundle/libphonenumber-js.min.js' {
  declare module.exports: $Exports<'libphonenumber-js/bundle/libphonenumber-js.min'>;
}
declare module 'libphonenumber-js/custom.js' {
  declare module.exports: $Exports<'libphonenumber-js/custom'>;
}
declare module 'libphonenumber-js/es6/as you type.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/as you type'>;
}
declare module 'libphonenumber-js/es6/common.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/common'>;
}
declare module 'libphonenumber-js/es6/format.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/format'>;
}
declare module 'libphonenumber-js/es6/get number type.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/get number type'>;
}
declare module 'libphonenumber-js/es6/metadata.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/metadata'>;
}
declare module 'libphonenumber-js/es6/parse.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parse'>;
}
declare module 'libphonenumber-js/es6/tools/compress.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/tools/compress'>;
}
declare module 'libphonenumber-js/es6/tools/download.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/tools/download'>;
}
declare module 'libphonenumber-js/es6/tools/generate.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/tools/generate'>;
}
declare module 'libphonenumber-js/es6/validate.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/validate'>;
}
declare module 'libphonenumber-js/index.common.js' {
  declare module.exports: $Exports<'libphonenumber-js/index.common'>;
}
declare module 'libphonenumber-js/index.es6.js' {
  declare module.exports: $Exports<'libphonenumber-js/index.es6'>;
}
declare module 'libphonenumber-js/runnable/download.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/download'>;
}
declare module 'libphonenumber-js/runnable/generate.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/generate'>;
}
declare module 'libphonenumber-js/runnable/metadata-branch.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/metadata-branch'>;
}
declare module 'libphonenumber-js/runnable/metadata-pull-request.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/metadata-pull-request'>;
}
declare module 'libphonenumber-js/runnable/metadata-unbranch.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/metadata-unbranch'>;
}
declare module 'libphonenumber-js/runnable/update.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/update'>;
}
declare module 'libphonenumber-js/webpack.config.babel.js' {
  declare module.exports: $Exports<'libphonenumber-js/webpack.config.babel'>;
}
