// flow-typed signature: 905689496f1f7040c6d8b2909d1e4ea0
// flow-typed version: <<STUB>>/react-native-camera-kit_vgithub:aksonov/react-native-camera-kit#21a3853e36ff233565ecc799e5c0d599631b6a1e/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-camera-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-camera-kit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-camera-kit/example/AlbumsScreen.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/example/AlbumsScreen.ios' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/example/app' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/example/CameraScreen' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/example/GalleryScreen.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/example/GalleryScreen.ios' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/example/scripts/quickinstall' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraKitCamera.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraKitCamera.ios' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraKitGallery.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraKitGallery.ios' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraKitGalleryView.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraKitGalleryView.ios' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreen.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreen.ios' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenBase' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenStyleObject.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenStyleObject.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-camera-kit/example/AlbumsScreen.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/example/AlbumsScreen.android'>;
}
declare module 'react-native-camera-kit/example/AlbumsScreen.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/example/AlbumsScreen.ios'>;
}
declare module 'react-native-camera-kit/example/app.js' {
  declare module.exports: $Exports<'react-native-camera-kit/example/app'>;
}
declare module 'react-native-camera-kit/example/CameraScreen.js' {
  declare module.exports: $Exports<'react-native-camera-kit/example/CameraScreen'>;
}
declare module 'react-native-camera-kit/example/GalleryScreen.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/example/GalleryScreen.android'>;
}
declare module 'react-native-camera-kit/example/GalleryScreen.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/example/GalleryScreen.ios'>;
}
declare module 'react-native-camera-kit/example/index.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/example/index.android'>;
}
declare module 'react-native-camera-kit/example/index.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/example/index.ios'>;
}
declare module 'react-native-camera-kit/example/scripts/quickinstall.js' {
  declare module.exports: $Exports<'react-native-camera-kit/example/scripts/quickinstall'>;
}
declare module 'react-native-camera-kit/index' {
  declare module.exports: $Exports<'react-native-camera-kit'>;
}
declare module 'react-native-camera-kit/index.js' {
  declare module.exports: $Exports<'react-native-camera-kit'>;
}
declare module 'react-native-camera-kit/src/CameraKitCamera.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraKitCamera.android'>;
}
declare module 'react-native-camera-kit/src/CameraKitCamera.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraKitCamera.ios'>;
}
declare module 'react-native-camera-kit/src/CameraKitGallery.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraKitGallery.android'>;
}
declare module 'react-native-camera-kit/src/CameraKitGallery.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraKitGallery.ios'>;
}
declare module 'react-native-camera-kit/src/CameraKitGalleryView.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraKitGalleryView.android'>;
}
declare module 'react-native-camera-kit/src/CameraKitGalleryView.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraKitGalleryView.ios'>;
}
declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreen.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreen.android'>;
}
declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreen.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreen.ios'>;
}
declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenBase.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenBase'>;
}
declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenStyleObject.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenStyleObject.android'>;
}
declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenStyleObject.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenStyleObject.ios'>;
}
