// flow-typed signature: 25569a435ad017c0b6e25f14575b634e
// flow-typed version: <<STUB>>/react-native-message-bar_v^1.6.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-message-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-message-bar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-message-bar/MessageBar' {
  declare module.exports: any;
}

declare module 'react-native-message-bar/MessageBarManager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-message-bar/index' {
  declare module.exports: $Exports<'react-native-message-bar'>;
}
declare module 'react-native-message-bar/index.js' {
  declare module.exports: $Exports<'react-native-message-bar'>;
}
declare module 'react-native-message-bar/MessageBar.js' {
  declare module.exports: $Exports<'react-native-message-bar/MessageBar'>;
}
declare module 'react-native-message-bar/MessageBarManager.js' {
  declare module.exports: $Exports<'react-native-message-bar/MessageBarManager'>;
}
