// flow-typed signature: 7841c8e150026fb5b6b0597a66a3e9bf
// flow-typed version: <<STUB>>/react-native-router-flux_vgithub:aksonov/react-native-router-flux#29090461469d4eb907072c63e9881f99205fab73/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-router-flux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-router-flux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-router-flux/__tests__/scenes.test' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/ActionConst' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Drawer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/index' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Lightbox' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/LightboxNavigator' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Modal' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/NavBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/navigationStore' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Overlay' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/OverlayNavigator' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Reducer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Router' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Scene' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Stack' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/State' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Tabs' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Util' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/drawer/DrawerContent' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/EchoView' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/Error' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/Home' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/Launch' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/lightbox/BaseLightbox' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/lightbox/DemoLightbox' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/Login' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/Login2' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/Login3' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/MessageBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/modal/BaseModal' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/modal/ErrorModal' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/Register' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/TabIcon' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/components/TabView' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/Example' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/Example/test/setup' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/ActionConst' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Drawer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/index' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Lightbox' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/LightboxNavigator' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Modal' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/NavBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/navigationStore' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Overlay' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/OverlayNavigator' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Reducer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Router' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Scene' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Stack' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/State' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Tabs' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Util' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-router-flux/__tests__/scenes.test.js' {
  declare module.exports: $Exports<'react-native-router-flux/__tests__/scenes.test'>;
}
declare module 'react-native-router-flux/dist/ActionConst.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/ActionConst'>;
}
declare module 'react-native-router-flux/dist/Drawer.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Drawer'>;
}
declare module 'react-native-router-flux/dist/index.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/index'>;
}
declare module 'react-native-router-flux/dist/Lightbox.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Lightbox'>;
}
declare module 'react-native-router-flux/dist/LightboxNavigator.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/LightboxNavigator'>;
}
declare module 'react-native-router-flux/dist/Modal.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Modal'>;
}
declare module 'react-native-router-flux/dist/NavBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/NavBar'>;
}
declare module 'react-native-router-flux/dist/navigationStore.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/navigationStore'>;
}
declare module 'react-native-router-flux/dist/Overlay.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Overlay'>;
}
declare module 'react-native-router-flux/dist/OverlayNavigator.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/OverlayNavigator'>;
}
declare module 'react-native-router-flux/dist/Reducer.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Reducer'>;
}
declare module 'react-native-router-flux/dist/Router.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Router'>;
}
declare module 'react-native-router-flux/dist/Scene.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Scene'>;
}
declare module 'react-native-router-flux/dist/Stack.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Stack'>;
}
declare module 'react-native-router-flux/dist/State.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/State'>;
}
declare module 'react-native-router-flux/dist/Tabs.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Tabs'>;
}
declare module 'react-native-router-flux/dist/Util.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Util'>;
}
declare module 'react-native-router-flux/Example/components/drawer/DrawerContent.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/drawer/DrawerContent'>;
}
declare module 'react-native-router-flux/Example/components/EchoView.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/EchoView'>;
}
declare module 'react-native-router-flux/Example/components/Error.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/Error'>;
}
declare module 'react-native-router-flux/Example/components/Home.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/Home'>;
}
declare module 'react-native-router-flux/Example/components/Launch.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/Launch'>;
}
declare module 'react-native-router-flux/Example/components/lightbox/BaseLightbox.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/lightbox/BaseLightbox'>;
}
declare module 'react-native-router-flux/Example/components/lightbox/DemoLightbox.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/lightbox/DemoLightbox'>;
}
declare module 'react-native-router-flux/Example/components/Login.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/Login'>;
}
declare module 'react-native-router-flux/Example/components/Login2.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/Login2'>;
}
declare module 'react-native-router-flux/Example/components/Login3.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/Login3'>;
}
declare module 'react-native-router-flux/Example/components/MessageBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/MessageBar'>;
}
declare module 'react-native-router-flux/Example/components/modal/BaseModal.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/modal/BaseModal'>;
}
declare module 'react-native-router-flux/Example/components/modal/ErrorModal.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/modal/ErrorModal'>;
}
declare module 'react-native-router-flux/Example/components/Register.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/Register'>;
}
declare module 'react-native-router-flux/Example/components/TabIcon.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/TabIcon'>;
}
declare module 'react-native-router-flux/Example/components/TabView.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/components/TabView'>;
}
declare module 'react-native-router-flux/Example/Example.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/Example'>;
}
declare module 'react-native-router-flux/Example/index.android.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/index.android'>;
}
declare module 'react-native-router-flux/Example/index.ios.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/index.ios'>;
}
declare module 'react-native-router-flux/Example/test/setup.js' {
  declare module.exports: $Exports<'react-native-router-flux/Example/test/setup'>;
}
declare module 'react-native-router-flux/src/ActionConst.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/ActionConst'>;
}
declare module 'react-native-router-flux/src/Drawer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Drawer'>;
}
declare module 'react-native-router-flux/src/index.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/index'>;
}
declare module 'react-native-router-flux/src/Lightbox.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Lightbox'>;
}
declare module 'react-native-router-flux/src/LightboxNavigator.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/LightboxNavigator'>;
}
declare module 'react-native-router-flux/src/Modal.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Modal'>;
}
declare module 'react-native-router-flux/src/NavBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/NavBar'>;
}
declare module 'react-native-router-flux/src/navigationStore.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/navigationStore'>;
}
declare module 'react-native-router-flux/src/Overlay.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Overlay'>;
}
declare module 'react-native-router-flux/src/OverlayNavigator.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/OverlayNavigator'>;
}
declare module 'react-native-router-flux/src/Reducer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Reducer'>;
}
declare module 'react-native-router-flux/src/Router.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Router'>;
}
declare module 'react-native-router-flux/src/Scene.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Scene'>;
}
declare module 'react-native-router-flux/src/Stack.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Stack'>;
}
declare module 'react-native-router-flux/src/State.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/State'>;
}
declare module 'react-native-router-flux/src/Tabs.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Tabs'>;
}
declare module 'react-native-router-flux/src/Util.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Util'>;
}
declare module 'react-native-router-flux/test/setup.js' {
  declare module.exports: $Exports<'react-native-router-flux/test/setup'>;
}
