// flow-typed signature: 9b1fa47e12029c5e548cb1e5f56044e5
// flow-typed version: <<STUB>>/react-native-radio-button_v^1.0.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-radio-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-radio-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-radio-button/RadioButton' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-radio-button/RadioButton.js' {
  declare module.exports: $Exports<'react-native-radio-button/RadioButton'>;
}
