// flow-typed signature: 2789201364902e90aeca606e53d9883c
// flow-typed version: <<STUB>>/react-native-background-geolocation_v^2.8.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-background-geolocation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-background-geolocation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-background-geolocation/RNBackgroundGeolocation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-background-geolocation/RNBackgroundGeolocation.js' {
  declare module.exports: $Exports<'react-native-background-geolocation/RNBackgroundGeolocation'>;
}
