// flow-typed signature: a962f387b4297daa1b6af2865c119ca3
// flow-typed version: <<STUB>>/react-native-actionsheet_v^2.2.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-actionsheet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-actionsheet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-actionsheet/lib/ActionSheetCustom' {
  declare module.exports: any;
}

declare module 'react-native-actionsheet/lib/ActionSheetIOS' {
  declare module.exports: any;
}

declare module 'react-native-actionsheet/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-actionsheet/lib/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-actionsheet/lib/ActionSheetCustom.js' {
  declare module.exports: $Exports<'react-native-actionsheet/lib/ActionSheetCustom'>;
}
declare module 'react-native-actionsheet/lib/ActionSheetIOS.js' {
  declare module.exports: $Exports<'react-native-actionsheet/lib/ActionSheetIOS'>;
}
declare module 'react-native-actionsheet/lib/index.js' {
  declare module.exports: $Exports<'react-native-actionsheet/lib/index'>;
}
declare module 'react-native-actionsheet/lib/styles.js' {
  declare module.exports: $Exports<'react-native-actionsheet/lib/styles'>;
}
