// flow-typed signature: 907153aad69c8adf53b919aa56780c3e
// flow-typed version: <<STUB>>/react-native-xmpp_vgithub:hippware/react-native-xmpp#0.5.11/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-xmpp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-xmpp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-xmpp/XmppDemo/__tests__/index.android' {
  declare module.exports: any;
}

declare module 'react-native-xmpp/XmppDemo/__tests__/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-xmpp/XmppDemo/components/ActivityIndicator' {
  declare module.exports: any;
}

declare module 'react-native-xmpp/XmppDemo/components/Conversation' {
  declare module.exports: any;
}

declare module 'react-native-xmpp/XmppDemo/components/Login' {
  declare module.exports: any;
}

declare module 'react-native-xmpp/XmppDemo/components/styles' {
  declare module.exports: any;
}

declare module 'react-native-xmpp/XmppDemo/index.android' {
  declare module.exports: any;
}

declare module 'react-native-xmpp/XmppDemo/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-xmpp/XmppDemo/stores/XmppStore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-xmpp/index' {
  declare module.exports: $Exports<'react-native-xmpp'>;
}
declare module 'react-native-xmpp/index.js' {
  declare module.exports: $Exports<'react-native-xmpp'>;
}
declare module 'react-native-xmpp/XmppDemo/__tests__/index.android.js' {
  declare module.exports: $Exports<'react-native-xmpp/XmppDemo/__tests__/index.android'>;
}
declare module 'react-native-xmpp/XmppDemo/__tests__/index.ios.js' {
  declare module.exports: $Exports<'react-native-xmpp/XmppDemo/__tests__/index.ios'>;
}
declare module 'react-native-xmpp/XmppDemo/components/ActivityIndicator.js' {
  declare module.exports: $Exports<'react-native-xmpp/XmppDemo/components/ActivityIndicator'>;
}
declare module 'react-native-xmpp/XmppDemo/components/Conversation.js' {
  declare module.exports: $Exports<'react-native-xmpp/XmppDemo/components/Conversation'>;
}
declare module 'react-native-xmpp/XmppDemo/components/Login.js' {
  declare module.exports: $Exports<'react-native-xmpp/XmppDemo/components/Login'>;
}
declare module 'react-native-xmpp/XmppDemo/components/styles.js' {
  declare module.exports: $Exports<'react-native-xmpp/XmppDemo/components/styles'>;
}
declare module 'react-native-xmpp/XmppDemo/index.android.js' {
  declare module.exports: $Exports<'react-native-xmpp/XmppDemo/index.android'>;
}
declare module 'react-native-xmpp/XmppDemo/index.ios.js' {
  declare module.exports: $Exports<'react-native-xmpp/XmppDemo/index.ios'>;
}
declare module 'react-native-xmpp/XmppDemo/stores/XmppStore.js' {
  declare module.exports: $Exports<'react-native-xmpp/XmppDemo/stores/XmppStore'>;
}
