// flow-typed signature: 40bf289f362f535ee380e99162b99450
// flow-typed version: <<STUB>>/react-native-carrier-info_vgithub:hippware/react-native-carrier-info/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-carrier-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-carrier-info' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-carrier-info/RNCarrierInfoDemo/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-carrier-info/RNCarrierInfoDemo/index.ios.js' {
  declare module.exports: $Exports<'react-native-carrier-info/RNCarrierInfoDemo/index.ios'>;
}
