// flow-typed signature: b6ef000ed89dee225bce778366035f7a
// flow-typed version: <<STUB>>/react-native-radio-buttons_v^0.13.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-radio-buttons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-radio-buttons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-radio-buttons/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-radio-buttons/lib/radio-buttons' {
  declare module.exports: any;
}

declare module 'react-native-radio-buttons/lib/segmented-controls' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-radio-buttons/lib/index.js' {
  declare module.exports: $Exports<'react-native-radio-buttons/lib/index'>;
}
declare module 'react-native-radio-buttons/lib/radio-buttons.js' {
  declare module.exports: $Exports<'react-native-radio-buttons/lib/radio-buttons'>;
}
declare module 'react-native-radio-buttons/lib/segmented-controls.js' {
  declare module.exports: $Exports<'react-native-radio-buttons/lib/segmented-controls'>;
}
