// flow-typed signature: 9b67e60144bbc7b1b6f16344cbed387d
// flow-typed version: <<STUB>>/stream-to-array_v^2.3.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-to-array'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-to-array' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stream-to-array/index' {
  declare module.exports: $Exports<'stream-to-array'>;
}
declare module 'stream-to-array/index.js' {
  declare module.exports: $Exports<'stream-to-array'>;
}
