// flow-typed signature: 471d9f6c1a757c2ec262e4a4603eb7b2
// flow-typed version: <<STUB>>/suncalc_v^1.8.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suncalc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suncalc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'suncalc/suncalc' {
  declare module.exports: any;
}

declare module 'suncalc/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'suncalc/suncalc.js' {
  declare module.exports: $Exports<'suncalc/suncalc'>;
}
declare module 'suncalc/test.js' {
  declare module.exports: $Exports<'suncalc/test'>;
}
